version: '2'
services:
    db:
        image: postgres:9.6
        volumes:
            - "./data/pg_data:/var/lib/postgresql/data"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=weather
            - POSTGRES_DB=weather
            - POSTGRES_PASSWORD=weather
