# Generated by Django 2.2.1 on 2019-05-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('pressure', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lux', models.IntegerField(blank=True, null=True)),
                ('uv_index', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('uv_a', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('uv_b', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RainMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rain_fall', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WindMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_direction', models.PositiveIntegerField(blank=True, choices=[(1, 'n'), (2, 'n-e'), (3, 'e'), (4, 's-e'), (5, 's'), (6, 's-w'), (7, 'w'), (8, 'n-w')], null=True)),
                ('wind_gust', models.IntegerField(blank=True, null=True)),
                ('wind_speed', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
