# Generated by Django 2.2.1 on 2019-06-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='uv_a',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='uv_b',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='uv_index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
