# Generated by Django 2.2.1 on 2019-06-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_station', '0002_auto_20190604_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='uv_a',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='uv_b',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
